### ISSUE TITLE
Create new Test RDS(Postgresql)

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/LiqwidsServices#1]
We will need a new empty test RDS set up under the New your water science center account
 probably something equivalent to WMA-icejams 

I'll also probably need AWS IAM account set up for this account as well.
(preferably by 4/18/2019)
- jeremy N

**Comment by DanielJBeckman** [comment]
Created and then killed. My understanding is that the group wants to wait for now. I will move this to on hold.
